[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci",
  "cd ../server && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd frontend && npx ng build --configuration production",
  "ls -la frontend/dist/",
  "ls -la frontend/dist/cars-maintenance/ || echo 'cars-maintenance folder not found'"
]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"