[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci",
  "cd ../server && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd frontend && npx ng build --configuration production",
  "echo '=== Frontend build completed ==='",
  "ls -la frontend/dist/",
  "ls -la frontend/dist/*/  || echo 'No subdirectory found'",
  "find frontend/dist -name 'index.html' -type f || echo 'index.html not found'",
  "echo '=== Build verification completed ==='"
]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"